### ISSUE TITLE
Markdown does not work in search

### ISSUE THREAD

**Issue by ME7DYCgw8M** [doug-101/TreeTag#4]
Markdown does not "render" in search results.

Reproducing issue

1. Edit configuration
2. Options
3. Enable markdown text formatting
4. add leaf node with markdown formatting, for example **bold**
5. see that **bolded** text is bold
6. search for that text in search
7. see that bold is raw text with asterisks on both sides

Big thank you for your programs, Treeline and Treetag.

Ps. is there some kind of feature roadmap?

**Comment by doug-101** [comment]
A fix has been pushed to GitHub and will be in the next release.

**Comment by doug-101** [comment]
This fix was included in the 0.7.3 release (just completed).
